// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using MosqueService;
using System;

namespace MosqueService.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20180106052529_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Mosan.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DateMade");

                    b.Property<string>("Description");

                    b.Property<string>("Priority");

                    b.HasKey("Id");

                    b.ToTable("MosqueAnncounments");
                });
#pragma warning restore 612, 618
        }
    }
}
